### ISSUE TITLE
Ping Bell example

### ISSUE THREAD

**Issue by jorgemonteiro** [LXJS/training-nodebots#33]
Guys, the Ping Bell example I create does not validate, the code works fine and makes a nice sound when I open a UDP connection to the server. Here is my code:

``` javascript
var five = require('johnny-five')
var dgram = require('dgram')

var board = new five.Board()
board.on('ready', function () {
    // Your solution here!
    piezo = new five.Piezo(8)
    var server = dgram.createSocket('udp4')

    server.on("error", function(err) {
        console.log("server error:\n" + err.stack)
        server.close();
    })
    server.on("message", function (msg, rinfo) {
        console.log("message received")
        piezo.song("cdfda ag cdfg gf ", "111111442111111442")
    })

    server.bind(1337)
 })
```

Can you please help me? I want to move on to the next exercise.

Thanks,
Jorge

**Comment by alanshaw** [comment]
What error message are you receiving? The code you've posted is correct, and validates when I run it.

P.S. you can move onto the next exercise and come back to this one - the workshop won't stop you from skipping ahead.

**Comment by alanshaw** [comment]
I'm seeing that the exercise isn't verifying for me when running on my Windows box. Will investigate and get back to you.

**Comment by jorgemonteiro** [comment]
1403042079918 Device(s) /dev/cu.usbserial-FAKEID
1403042080336 Connected /dev/cu.usbserial-FAKEID
1403042080338 Repl Initialized

> > Please wait while your solution is tested...
> > Could not verify: Piezo didn't play a tone when sent a UDP message: expected 0 t
> > o be above 0

**Comment by jorgemonteiro** [comment]
Another problem with the fire alarm, here is my code, maybe it is wrong but it behaves properly on my Sparkfun RedBoard:

``` javascript
var five = require('johnny-five')

var disableAlarm = false
var alarmOn = false

var board = new five.Board()
board.on('ready', function () {
    // Your solution here!
    var tmp36 = new five.Sensor("A0")
    var led = new five.Led(13)
    var piezo = new five.Piezo(9)
    var button = new five.Button(5)

    tmp36.on("data", function() {
        var celsius = ((this.value * 0.004882814) - 0.5) * 100;
        if (celsius > 50) {
            if (!alarmOn && !disableAlarm) {
                led.on();
                piezo.song("cdfda ag cdfg gf ", "111111442111111442")
                alarmOn = true
            }
        } else {
            disableAlarm = false
        }
    });

    button.on("press", function() {
        disableAlarm = true
        led.off()
    });
 })
```

Error code is:

c:\Users\jmonteiro\source\workshop>nodebot-workshop verify fire-alarm.js
1403105670900 Device(s) /dev/cu.usbserial-FAKEID
1403105671319 Connected /dev/cu.usbserial-FAKEID
1403105671321 Repl Initialized

> > Please wait while your solution is tested...
> > Could not verify: LED was not turned off when fire stopped: expected false to be
> >  true

**Comment by jorgemonteiro** [comment]
Also, one more question... is there a way for me to stop the Piezo while the song is playing?

**Comment by alanshaw** [comment]
@jorgemonteiro the latest version of the workshopper (v2.0.2) should verify your solution to ping bell correctly.

**Comment by alanshaw** [comment]
@jorgemonteiro wrt your fire alarm solution, if the temperature drops below 50 your alarm doesn't turn itself off - this is why it doesn't verify.

Hope that helps!
